audit_on_steroid:
  outputs:
    dev:
      dbname: data_warehouse
      host: localhost
      pass: '123456'
      port: 5432
      schema: 'prefex_'
      threads: 1
      type: postgres
      user: postgres
  target: dev